import { Appointment, Barber, Customer, FinancialTransaction, LoyaltyReward, PortfolioPhoto, Review, SalonConfig, Service } from './types';
import { SALON } from './config/salon';

export const INITIAL_SALON_CONFIG: SalonConfig = {
  name: SALON.nome,
  tagline: SALON.slogan,
  address: SALON.endereco.completo,
  phone: SALON.telefone,
  whatsappNumber: SALON.whatsapp,
  pixKey: SALON.pix.chave,
  pixKeyType: SALON.pix.tipo,
  pixBeneficiary: `${SALON.pix.beneficiario} - CNPJ ${SALON.pix.cnpj}`,
  pixCity: SALON.pix.cidade,
  instagram: SALON.instagram,
  openingHours: SALON.horariosResumo,
  loyaltyStampsGoal: SALON.regras.selosMeta,
  toleranceMinutes: SALON.regras.toleranciaMinutos,
  holidaySurcharge: SALON.regras.acrescimoFeriados,
  referencePoint: SALON.endereco.referencia,
};

export const INITIAL_SERVICES: Service[] = SALON.servicos.map(s => ({
  id: s.id,
  name: s.nome,
  category: s.categoria,
  description: `${s.nome} — serviço profissional.`,
  price: s.preco,
  durationMinutes: s.duracaoMinutos,
  pointsReward: s.pontos,
  popular: s.categoria === 'combos',
}));

export const INITIAL_BARBERS: Barber[] = SALON.barbeiros.map(b => ({
  id: b.id,
  name: b.nome,
  role: b.especialidade,
  avatarUrl: b.foto,
  rating: b.avaliacao,
  reviewsCount: b.totalAvaliacoes,
  specialties: ['Degradê', 'Cortes Clássicos', 'Barba'],
  phone: b.telefone,
  bio: `${b.nome} — ${b.especialidade}.`,
  availableDays: [0, 1, 2, 3, 4, 5, 6],
}));

export const INITIAL_LOYALTY_REWARDS: LoyaltyReward[] = [
  {
    id: 'rew-1',
    title: '50% OFF no Próximo Corte',
    description: 'Válido para qualquer modalidade de corte de cabelo.',
    pointsCost: 250,
    stampsRequired: 5,
    badge: '5 Selos',
    type: 'stamps',
  },
  {
    id: 'rew-2',
    title: 'Corte ou Barboterapia GRÁTIS',
    description: `Complete ${SALON.regras.selosMeta} selos no seu cartão fidelidade e ganhe um atendimento 100% gratuito!`,
    pointsCost: 500,
    stampsRequired: SALON.regras.selosMeta,
    badge: `${SALON.regras.selosMeta} Selos (Grátis)`,
    type: 'stamps',
  },
  {
    id: 'rew-3',
    title: 'Pomada Modeladora Efeito Matte',
    description: 'Resgate um pote da pomada premium exclusiva da nossa barbearia.',
    pointsCost: 350,
    badge: '350 Pontos',
    type: 'points',
  },
  {
    id: 'rew-4',
    title: 'Óleo Hidratante para Barba',
    description: 'Óleo nobre com aroma de sândalo e cravo para maciez e brilho da barba.',
    pointsCost: 300,
    badge: '300 Pontos',
    type: 'points',
  },
  {
    id: 'rew-5',
    title: 'Cerveja Artesanal Cortesia',
    description: 'Deguste uma gelada especial durante o seu atendimento.',
    pointsCost: 100,
    badge: '100 Pontos',
    type: 'points',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    customerName: 'João Pedro',
    barberId: 'barber-1',
    barberName: SALON.barbeiros[0]?.nome || 'Barbeiro',
    rating: 5,
    comment: 'Atendimento fora de série! O degradê e o alinhamento ficaram perfeitos. Recomendo demais!',
    tags: ['Degradê Impecável', 'Pontualidade', 'Ambiente 10/10'],
    createdAt: '2026-09-04T15:30:00Z',
  },
  {
    id: 'rev-2',
    customerName: 'Lucas Oliveira',
    barberId: 'barber-2',
    barberName: SALON.barbeiros[1]?.nome || 'Barbeiro',
    rating: 5,
    comment: 'O atendimento com a toalha e o cuidado na barba é excelente. Ambiente de primeira e atendimento rápido!',
    tags: ['Barboterapia', 'Relaxamento', 'Mão Leve'],
    createdAt: '2026-09-03T18:10:00Z',
  },
  {
    id: 'rev-3',
    customerName: 'Rafael Costa',
    barberId: 'barber-1',
    barberName: SALON.barbeiros[0]?.nome || 'Barbeiro',
    rating: 5,
    comment: `Melhor barbearia da região! O corte navalhado dura muito tempo impecável e o agendamento no app facilita demais.`,
    tags: ['Degradê Impecável', 'Precisão'],
    createdAt: '2026-09-02T11:45:00Z',
  },
  {
    id: 'rev-4',
    customerName: 'Matheus Lima',
    barberId: 'barber-1',
    barberName: SALON.barbeiros[0]?.nome || 'Barbeiro',
    rating: 5,
    comment: 'Trouxe meu filho para o corte kids e o atendimento foi nota 10. Muita paciência e o corte ficou estiloso demais.',
    tags: ['Atendimento Kids', 'Profissionalismo'],
    createdAt: '2026-08-30T17:20:00Z',
  },
  {
    id: 'rev-5',
    customerName: 'Felipe Souza',
    barberId: 'barber-2',
    barberName: SALON.barbeiros[1]?.nome || 'Barbeiro',
    rating: 5,
    comment: 'O app é sensacional, agendei em 30 segundos e a confirmação no WhatsApp garante tudo sem precisar ficar ligando. Top!',
    tags: ['Agendamento Rápido', 'Notificação WhatsApp'],
    createdAt: '2026-08-28T14:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cli-1',
    name: 'João Pedro',
    phone: '11999990001',
    email: 'joao.pedro@email.com',
    totalVisits: 8,
    totalSpent: 620,
    loyaltyStamps: 8,
    loyaltyPoints: 480,
    tier: 'Ouro VIP',
    lastVisit: '2026-09-04',
    preferredBarberId: 'barber-1',
    notes: 'Prefere corte com tesoura nas pontas.',
  },
  {
    id: 'cli-2',
    name: 'Lucas Oliveira',
    phone: '11999990002',
    email: 'lucas.oliveira@email.com',
    totalVisits: 5,
    totalSpent: 375,
    loyaltyStamps: 5,
    loyaltyPoints: 290,
    tier: 'Prata',
    lastVisit: '2026-09-03',
    preferredBarberId: 'barber-2',
    notes: 'Pele sensível na lâmina, usar pós-barba sem álcool.',
  },
  {
    id: 'cli-3',
    name: 'Rafael Costa',
    phone: '11999990003',
    email: 'rafael.costa@email.com',
    totalVisits: 12,
    totalSpent: 1050,
    loyaltyStamps: 2,
    loyaltyPoints: 620,
    tier: 'Ouro VIP',
    lastVisit: '2026-09-02',
    preferredBarberId: 'barber-1',
    notes: 'Cliente fiel semanal. Gosta de fade militar baixo.',
  },
  {
    id: 'cli-4',
    name: 'Matheus Lima',
    phone: '11999990004',
    email: 'matheus.lima@email.com',
    totalVisits: 3,
    totalSpent: 225,
    loyaltyStamps: 3,
    loyaltyPoints: 170,
    tier: 'Bronze',
    lastVisit: '2026-08-30',
    preferredBarberId: 'barber-1',
  },
  {
    id: 'cli-5',
    name: 'Felipe Souza',
    phone: '11999990005',
    email: 'felipe.souza@email.com',
    totalVisits: 6,
    totalSpent: 450,
    loyaltyStamps: 6,
    loyaltyPoints: 340,
    tier: 'Prata',
    lastVisit: '2026-08-25',
    preferredBarberId: 'barber-2',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    customerName: 'João Pedro',
    customerPhone: '11999990001',
    serviceIds: ['srv-2'],
    serviceNames: ['Corte Degradê'],
    totalPrice: SALON.servicos[1]?.preco || 50,
    totalDurationMinutes: SALON.servicos[1]?.duracaoMinutos || 40,
    barberId: 'barber-1',
    barberName: SALON.barbeiros[0]?.nome || 'Barbeiro',
    date: new Date().toISOString().split('T')[0],
    time: '09:00',
    status: 'confirmed',
    paymentMethod: 'presencial',
    paymentStatus: 'no_local',
    whatsappNotificationSent: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'apt-2',
    customerName: 'Lucas Oliveira',
    customerPhone: '11999990002',
    serviceIds: ['srv-3'],
    serviceNames: ['Barba Simples'],
    totalPrice: SALON.servicos[2]?.preco || 35,
    totalDurationMinutes: SALON.servicos[2]?.duracaoMinutos || 30,
    barberId: 'barber-2',
    barberName: SALON.barbeiros[1]?.nome || 'Barbeiro',
    date: new Date().toISOString().split('T')[0],
    time: '10:00',
    status: 'confirmed',
    paymentMethod: 'presencial',
    paymentStatus: 'no_local',
    whatsappNotificationSent: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'apt-3',
    customerName: 'Rafael Costa',
    customerPhone: '11999990003',
    serviceIds: ['srv-1'],
    serviceNames: ['Corte Social'],
    totalPrice: SALON.servicos[0]?.preco || 45,
    totalDurationMinutes: SALON.servicos[0]?.duracaoMinutos || 30,
    barberId: 'barber-1',
    barberName: SALON.barbeiros[0]?.nome || 'Barbeiro',
    date: new Date().toISOString().split('T')[0],
    time: '14:00',
    status: 'confirmed',
    paymentMethod: 'presencial',
    paymentStatus: 'no_local',
    whatsappNotificationSent: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'apt-4',
    customerName: 'Matheus Lima',
    customerPhone: '11999990004',
    serviceIds: ['srv-4'],
    serviceNames: ['Cabelo + Barba'],
    totalPrice: SALON.servicos[3]?.preco || 75,
    totalDurationMinutes: SALON.servicos[3]?.duracaoMinutos || 50,
    barberId: 'barber-2',
    barberName: SALON.barbeiros[1]?.nome || 'Barbeiro',
    date: new Date().toISOString().split('T')[0],
    time: '16:00',
    status: 'confirmed',
    paymentMethod: 'presencial',
    paymentStatus: 'no_local',
    whatsappNotificationSent: false,
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_TRANSACTIONS: FinancialTransaction[] = [
  {
    id: 'tx-1',
    appointmentId: 'apt-100',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 125,
    date: '2026-09-02',
    paymentMethod: 'pix',
    description: `Atendimento Rafael Costa - Degradê + Barba`,
    barberId: 'barber-1',
  },
  {
    id: 'tx-2',
    appointmentId: 'apt-101',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 110,
    date: '2026-09-06',
    paymentMethod: 'pix',
    description: `Atendimento João Pedro - Combo Completo`,
    barberId: 'barber-1',
  },
  {
    id: 'tx-3',
    appointmentId: 'apt-102',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 75,
    date: '2026-09-06',
    paymentMethod: 'cartao',
    description: `Atendimento Lucas Oliveira - Cabelo + Barba`,
    barberId: 'barber-2',
  },
  {
    id: 'tx-4',
    type: 'receita',
    category: 'Venda de Produtos',
    amount: 85,
    date: '2026-09-05',
    paymentMethod: 'cartao',
    description: 'Venda de 1 Pomada Matte + 1 Óleo para Barba',
  },
  {
    id: 'tx-5',
    type: 'despesa',
    category: 'Insumos e Lâminas',
    amount: 140,
    date: '2026-09-04',
    paymentMethod: 'pix',
    description: 'Compra de caixas de lâminas descartáveis e toalhas esterilizadas',
  },
  {
    id: 'tx-6',
    type: 'despesa',
    category: 'Frigobar & Café Especial',
    amount: 95,
    date: '2026-09-03',
    paymentMethod: 'pix',
    description: 'Reposição de grãos de café gourmet e cervejas artesanais cortesia',
  },
  {
    id: 'tx-7',
    type: 'receita',
    category: 'Serviços de Barbearia',
    amount: 180,
    date: '2026-09-04',
    paymentMethod: 'pix',
    description: 'Atendimentos de quarta-feira tarde',
    barberId: 'barber-2',
  },
];

export const INITIAL_PORTFOLIO: PortfolioPhoto[] = [
  {
    id: 'port-1',
    barberId: 'barber-1',
    barberName: SALON.barbeiros[0]?.nome || 'Barbeiro',
    barberAvatar: SALON.logo,
    title: 'Pompadour Texturizado & Fade Esculpido',
    styleTag: 'Pompadour Clássico',
    category: 'classico',
    imageUrl: 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=800&auto=format&fit=crop&q=80',
    description: 'Transição suave iniciada na navalha com topo estruturado em tesoura. Finalização com pomada matte.',
    likesCount: 184,
    createdAt: '2026-09-04',
    suggestedServiceName: 'Cabelo + Barba',
  },
  {
    id: 'port-2',
    barberId: 'barber-1',
    barberName: SALON.barbeiros[0]?.nome || 'Barbeiro',
    barberAvatar: SALON.logo,
    title: 'Corte Tradicional com Visagismo',
    styleTag: 'Tesoura & Visagismo',
    category: 'classico',
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800&auto=format&fit=crop&q=80',
    description: 'Harmonização de traços faciais through de proporções balanceadas na tesoura.',
    likesCount: 142,
    createdAt: '2026-09-02',
    suggestedServiceName: 'Corte Social',
  },
  {
    id: 'port-3',
    barberId: 'barber-1',
    barberName: SALON.barbeiros[0]?.nome || 'Barbeiro',
    barberAvatar: SALON.logo,
    title: 'Barba Esculpida & Alinhamento',
    styleTag: 'Barba de Respeito',
    category: 'barba',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80',
    description: 'Contorno de bochechas com navalhete e toalha quente com essência de menta.',
    likesCount: 226,
    createdAt: '2026-08-30',
    suggestedServiceName: 'Barba Simples',
  },
  {
    id: 'port-4',
    barberId: 'barber-2',
    barberName: SALON.barbeiros[1]?.nome || 'Barbeiro',
    barberAvatar: SALON.logo,
    title: 'Mid Skin Fade com Texturização',
    styleTag: 'Mid Skin Fade',
    category: 'fade',
    imageUrl: 'https://images.unsplash.com/photo-1567894340315-735d7c361db0?w=800&auto=format&fit=crop&q=80',
    description: 'Degradê em 4 alturas partindo da pele com sombreamento uniforme.',
    likesCount: 310,
    createdAt: '2026-09-05',
    suggestedServiceName: 'Corte Degradê',
  },
  {
    id: 'port-5',
    barberId: 'barber-2',
    barberName: SALON.barbeiros[1]?.nome || 'Barbeiro',
    barberAvatar: SALON.logo,
    title: 'Low Taper Fade Urbano',
    styleTag: 'Taper Fade',
    category: 'fade',
    imageUrl: 'https://images.unsplash.com/photo-1517832606589-7629c339590a?w=800&auto=format&fit=crop&q=80',
    description: 'Desvanecimento apenas nas costeletas e na nuca, preservando o volume.',
    likesCount: 195,
    createdAt: '2026-09-01',
    suggestedServiceName: 'Corte Degradê',
  },
  {
    id: 'port-6',
    barberId: 'barber-2',
    barberName: SALON.barbeiros[1]?.nome || 'Barbeiro',
    barberAvatar: SALON.logo,
    title: 'High Fade com Topete Alto',
    styleTag: 'High Fade Navalhado',
    category: 'fade',
    imageUrl: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&auto=format&fit=crop&q=80',
    description: 'Raspagem alta com transição limpa para clientes que buscam impacto.',
    likesCount: 168,
    createdAt: '2026-08-28',
    suggestedServiceName: 'Corte Degradê',
  },
];
